theme = "book"
title = "Bruno Henriques"
canonifyURLs = "true"

[markup.goldmark.renderer]
  unsafe = true

[params]
  BookTheme = 'dark'
  BookRepo = "https://github.com/bphenriques/knowledge-base"

  BookSection = '*'

  # Custom as the exported files have `.md` extension and not the original `.org` extension.
  OrgBookEditPath = 'edit/master/org'
