theme = "tagged-notes"
title = "Bruno Henriques's Digital Garden ðŸŒ±"
canonifyURLs = "true"

[markup.goldmark.renderer]
  unsafe = true

[outputs]
  home = ["HTML"]

[params]
  BrandTitle = 'Bruno Henriques'
  BookTheme = 'dark'
  HomePage = 'https://bphenriques.github.io'
