theme = "tagged-notes"
title = "Bruno Henriques"
canonifyURLs = "true"

[markup.goldmark.renderer]
  unsafe = true

[outputs]
  home = ["HTML"]

[params]
  BookTheme = 'dark'
  HomePage = 'https://bphenriques.github.io'
